services:
  backend:
    build:
      context: ./api.carbontrack.nexsecure.fr
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_OCR_TESSERACTPATH: ${APP_OCR_TESSERACTPATH:-/usr/bin/tesseract}
      APP_OCR_LANG: ${APP_OCR_LANG:-fra}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
